project:
  type: website
  output-dir: docs

website:
  title: "Taib Biygautane"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Research.qmd
        text: Research
      - href: https://jkbirnir.github.io/GVPT729B/
        text: GVPT729B
      - href: Teaching.qmd
        text: Teaching

format:
  html:
    theme: Zephyr
    css: styles.css
    toc: true

editor: visual